# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the prd_CSsharp_UTN_LaboII branch
  push:
    branches: [ prd_CSsharp_UTN_LaboII ]
  pull_request:
    branches: [ prd_CSsharp_UTN_LaboII ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pr_check:
    runs-on: ubuntu-latest
    name: A job to Post comment on PR
    steps:
    - uses: actions/checkout@v2
    - name: PR Action
      uses: koushikmohan1996/action-pr-gifs@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
